name: Publish Public Files

on:
  push:
    branches:
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Get all history

      - name: Update main branch
        run: |
          # Use the standard Actions bot for the commit for better security and standards
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git checkout main

          # Stage all files for removal to ensure a clean slate.
          git rm -rf .

          # Re-introduce the README.md from the dev branch to preserve it.
          git checkout dev -- README.md

          # Define the source folder from 'dev' that you want to publish
          SOURCE_FOLDER="EV_main"

          # Copy all files from the source folder to the root of the main branch.
          if [ -d "dev/$SOURCE_FOLDER" ] && [ -n "$(ls -A "dev/$SOURCE_FOLDER")" ]; then
            cp -r "dev/$SOURCE_FOLDER"/* .
          fi

          git add .
          git commit --allow-empty -m "Deploy: Sync files from dev/EV_main to main"
          # Force push to overwrite the main branch completely. This is necessary
          # to avoid conflicts with the old history.
          git push --force origin main
