name: Publish Curated Files to Main Branch

on:
  push:
    branches:
      - dev # Trigger the workflow on pushes to the 'dev' branch

jobs:
  publish:
    runs-on: ubuntu-latest
    # Grant permission for the action to push to the repository
    permissions:
      contents: write

    steps:
      - name: Checkout dev branch content
        uses: actions/checkout@v4
        with:
          # A Personal Access Token (PAT) is required to trigger subsequent workflows
          # or to push to a protected branch if you set one up.
          token: ${{ secrets.GH_PAT }}

      - name: Stage Files for Publication
        run: |
          echo "--- Preparing files for the 'main' branch ---"
          # Create a temporary directory to hold the files for the main branch.
          # This ensures no unwanted files are accidentally included.
          mkdir public
          
          # --- CONFIGURATION ---
          # This is the primary configuration for the workflow.
          # Add the names of all files and directories you want to publish to the 'main' branch.
          # Paths are relative to the root of your repository.
          ITEMS_TO_PUBLISH=(
            "README.md"
            "EV_analysis"
            "EV_results"
            "EV_proposal/EV_proposal.pdf"
          )

          echo "--- Copying specified items to the public directory ---"
          for item in "${ITEMS_TO_PUBLISH[@]}"; do
            if [ -e "$item" ]; then
              echo "Copying '$item'..."
              # Use -r to copy directories recursively
              cp -r "$item" public/
            else
              echo "Warning: Item '$item' not found in 'dev' branch. Skipping."
            fi
          done

          echo "--- Final structure of the public directory: ---"
          # List the contents for debugging purposes.
          ls -laR public

      - name: Deploy to main branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          # The PAT you created and stored in repository secrets.
          personal_token: ${{ secrets.GH_PAT }}
          # The branch to publish to.
          publish_branch: main
          # The directory containing the files to be published.
          publish_dir: ./public
          # This option creates a commit with no parent history on the 'main' branch.
          # It's perfect for keeping the public branch clean and separate from the 'dev' history.
          force_orphan: true
          # The user details for the commit.
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          # The commit message for the deployment.
          commit_message: "Deploy: Sync public files to main"
