
// Standard Modules - all from AnalysisToolbox
include { participant_discovery; finalize_participant } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'

// EmotiView pipeline Modules - all using IOInterface from AnalysisToolbox
// readers
include { IOInterface as txt_reader } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as xdf_reader } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
// extractor
include { IOInterface as extracting_processor } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
// filterers
include { IOInterface as eda_filtering_processor } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as ecg_filtering_processor } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as eeg_filtering_processor } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as fnirs_filtering_processor } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
// peak detector
include { IOInterface as peak_detection_processor } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
// referencer
include { IOInterface as referencing_processor } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
// transforms
include { IOInterface as log_transform_processor } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as tddr_processor } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as linear_transform_processor } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
// event processor
include { IOInterface as events_processor } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
// tree builder
include { IOInterface as tree_processor } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
// epochers
include { IOInterface as eda_epoching_processor } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as ecg_epoching_processor } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as eeg_epoching_processor } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as fnirs_epoching_processor } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
// analyzers
include { IOInterface as ic_analyzer } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as interval_analyzer } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as amplitude_analyzer } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as psd_analyzer } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as fai1_analyzer } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as fai2_analyzer } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as fai3_analyzer } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as group_analyzer } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as panas_analyzer } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as bisbas_analyzer } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as sam_analyzer } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as be7_analyzer } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as ea11_analyzer } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
// concatenators
include { IOInterface as sam_concatenating_processor } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as be7_concatenating_processor } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as ea11_concatenating_processor } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as hrv_concatenating_processor } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as eda_concatenating_processor } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as psd_concatenating_processor } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as fai_concatenating_processor } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as fnirs_concatenating_processor } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
// plot data merger (generic - combines plot-ready data from multiple sources)
include { IOInterface as fai_merger } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
// relative normalizers (baseline normalization to NEU condition)
include { IOInterface as hrv_relative_analyzer } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as eda_relative_analyzer } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as psd_relative_analyzer } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as fai_relative_analyzer } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as fnirs_relative_analyzer } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as fai_combined_relative_analyzer } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
// plotters
include { IOInterface as panas_plotter } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as bisbas_plotter } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as sam_plotter } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as be7_plotter } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as ea11_plotter } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as hrv_plotter } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as eda_plotter } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as psd_plotter } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as fai_plotter } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as fnirs_plotter } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as fai_combined_plotter } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as hrv_rel_plotter } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as eda_rel_plotter } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as psd_rel_plotter } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as fai_rel_plotter } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as fnirs_rel_plotter } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as fai_combined_rel_plotter } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
// file finders
include { IOInterface as aux_file_finder } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as eda_file_finder } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as ecg_file_finder } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as trigger_file_finder } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as eeg_file_finder } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as eeg_cleaned_file_finder } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as sam1_file_finder } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as sam2_file_finder } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as sam3_file_finder } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as be71_file_finder } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as be72_file_finder } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as be73_file_finder } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as ea111_file_finder } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as ea112_file_finder } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as ea113_file_finder } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as eda1_file_finder } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as eda2_file_finder } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as eda3_file_finder } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as hrv1_file_finder } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as hrv2_file_finder } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as hrv3_file_finder } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as psd1_file_finder } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as psd2_file_finder } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as psd3_file_finder } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as psd1_raw_file_finder } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as psd2_raw_file_finder } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as psd3_raw_file_finder } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as fnirs_file_finder } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as fnirs1_file_finder } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as fnirs2_file_finder } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as fnirs3_file_finder } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
// fnirs asymmetry input file finders (separate from fnirs concat file finders)
include { IOInterface as fnirs_asym_input1_file_finder } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as fnirs_asym_input2_file_finder } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as fnirs_asym_input3_file_finder } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
// fnirs asymmetry (hemispheric R-L)
include { IOInterface as fnirs_asym1_analyzer } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as fnirs_asym2_analyzer } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as fnirs_asym3_analyzer } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as fnirs_asym_concatenating_processor } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as fnirs_asym_relative_analyzer } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as fnirs_asym_plotter } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
include { IOInterface as fnirs_asym_rel_plotter } from '../../AnalysisToolbox/Python/utils/workflow_wrapper.nf'
