This is makeindex, version 2.16 [MiKTeX 24.1].
Scanning style file ./EV_thesis.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file EV_thesis.acn....done (161 entries accepted, 0 rejected).
Sorting entries....done (1260 comparisons).
Generating output file EV_thesis.acr....done (92 lines written, 0 warnings).
Output written in EV_thesis.acr.
Transcript written in EV_thesis.alg.
