This is makeindex, version 2.16 [MiKTeX 24.1].
Scanning style file ./EV_proposal.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file EV_proposal.acn....done (197 entries accepted, 0 rejected).
Sorting entries.....done (1649 comparisons).
Generating output file EV_proposal.acr....done (92 lines written, 0 warnings).
Output written in EV_proposal.acr.
Transcript written in EV_proposal.alg.
